### ISSUE TITLE
프로덕트 관련 기능

### ISSUE THREAD

**Issue by jeongmooon** [whatpl/whatpl-backend#23]
## 어떤 기능인가요?

- 프로덕트 등록
   - 제목, 상세내용, 팀원, 출시 여부 필수사항으로 체크

- 프로덕트 열람
  - 조회 수 체크
  - 북마크 기능
  
- 프로덕트에 댓글 기능
  - 프로덕트에 댓글 기능 추가
  - 2depth 형태로  첫 댓글 시에만 평점 부여 가능
  - 평점은 댓글이 가지고 있음

- 프로덕트 리스트
  - 로고 이미지, 제목, 한줄 소개, 북마크 수, 북마크 등록 아이콘, 평점, 출시 타입, 업데이트 일자
  -  키워드 검색기

## 작업 상세 내용

- [ ] Product - Review (1:N)
- [ ] Product - Member(N:N)
- [ ] Create 시에 validation 체크
- [ ] Product BookMarking 기능 추가여부 확인
- [ ] Review - 2Depth

**Comment by shin-je-woo** [comment]
기획 삭제로 close합니다.
